---
# Playbook to provision the CTF dev environment

# picoCTF
- hosts: dev.ctf.localhost
  remote_user: "{{ ansible_user }}"
  become: yes
  become_method: sudo
  pre_tasks:
    - name: Copy Source to non synced directory
      synchronize:
        src: /sync/picoCTF/
        dest: /picoCTF
      delegate_to: "{{ inventory_hostname }}"
      tags: ["sync"]
  roles:
    - {role: common     , tags: ["common"]}
    - {role: mongodb    , tags: ["db"]}
    - {role: pico-shell , tags: ["shell"]}
    - {role: pico-web   , tags: ["web"]}

# CTFd
- hosts: dev.ctf.localhost
  remote_user: "{{ ansible_user }}"
  roles:
    - {role: docker    , tags: ["docker"], become: yes}
  post_tasks:
    - name: Copy Source to non synced directory
      synchronize:
        src: /CTFd
        dest: ~/CTFd
      delegate_to: "{{ inventory_hostname }}"

    - name: Create Secret Key
      shell: python -c "import os; f=open('.ctfd_secret_key', 'a+'); f.write(os.urandom(64)); f.close()"
      args:
        chdir: ~/CTFd
      tags: ["ctfd"]

    - name: Start CTFd
      shell: docker-compose up -d
      args:
        chdir: ~/CTFd
      tags: ["ctfd"]

# workshop
- hosts: dev.ctf.localhost
  remote_user: "{{ ansible_user }}"
  roles:
  tasks:
    - name: Clone workshop repo
      git:
        repo: 'https://github.com/royragsdale/avengercon-taoccc.git'
        dest: ~/workshop
      tags: ["workshop"]
