---
# install docker-compose

- name: Download and install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    checksum: "{{docker_compose_checksum}}"

- name: Set docker-compose executable
  file:
    path: /usr/local/bin/docker-compose
    state: file
    mode: "+x"

- name: Download and install command completion
  get_url:
    url: "https://raw.githubusercontent.com/docker/compose/{{docker_compose_version}}/contrib/completion/bash/docker-compose"
    dest: /etc/bash_completion.d/docker-compose
